### ISSUE TITLE
Video component jagged / jumpy in export

### ISSUE THREAD

**Issue by TiborUdvari** [JonnyBurger/remotion#135] opened 2021-02-23 09:37 UTC
I have added a video a webm video to the project as per documentation. Once I export it misses frames and isn't smooth. Is there any special way to encode the video to make it work? Or is this a known problem?

**Comment by jonlambert** [comment] 2021-02-23 09:40
Dupe of https://github.com/JonnyBurger/remotion/issues/62 but the good news is this appears to be fixed in an upcoming version 🙂

**Comment by JonnyBurger** [comment] 2021-02-24 07:25
Probably solved in main branch, thanks @jonlambert!

Can you try out 1.4.0-alpha.2777f01c on NPM (upgrade all packages that have remotion in the name, make sure to have no `^` tilde in the package.json) and see if the problem is solved?

It would give some confidence that this problem is indeed solved in 1.4 (which should come out this week still).

**Comment by jonlambert** [comment] 2021-02-24 13:44
No luck on my end unfortunately @JonnyBurger. I'm still getting jagged/jumpy frames on export (and timing drift in preview). 

@TiborUdvari may have better luck, though. I'll see if I can dig out a public video to reproduce the issue with later.

**Comment by cnnrhill** [comment] 2021-02-24 22:35
I can also confirm this is still an issue with the alpha version.

**Comment by JonnyBurger** [comment] 2021-02-25 16:13
@jonlambert @TiborUdvari I've tested it myself recently too and didn't notice it, so it would be great if you can send a video where the problem appears! You can also send privately to hi@jonny.io and I'll take a look!

**Comment by TiborUdvari** [comment] 2021-02-25 21:31
Just updated, works for me 🎉

**Comment by monophthongal** [comment] 2021-02-25 23:36
I had this issue with 1.3 (and the alpha version) but it seems to be resolved in 1.4. I tried rendering a video that had previously been having major jitter / frame skipping issues and it looks great now. Will let you know if it happens again.

**Comment by JonnyBurger** [comment] 2021-02-26 06:46
That’s great to hear! Then I'm closing the issue. I’m sorry the alpha didn’t work, I suspect it could be how NPM resolves versions and you didn’t get the correct alpha from my instructions. Trying to learn from that for next time 😄

**Closed by JonnyBurger** 2021-02-26 06:46 UTC

**Comment by somebody32** [comment] 2021-03-01 16:30
Just for anyone who would find that issue: I've managed to solve it but scaling down concurrency to 1. As soon as my animation was using React's state, I assume that race conditions caused the "jumpiness."

**Comment by JonnyBurger** [comment] 2021-03-02 08:59
@somebody32 I think the better solution is to upgrade to the newest version! `npm run upgrade` in your project. Then you don't need to slow down the render process.
If there is still an issue with the newest version, please report it.

**Comment by somebody32** [comment] 2021-03-02 09:19
@JonnyBurger, unfortunately, that happened with the latest version. Will open a new issue then, thanks!

**Comment by JonnyBurger** [comment] 2021-03-02 09:20
Ok, thanks for reporting!
If you can attach the video with which it's happening it would be great. You can also email it to me hi@jonny.io if you don't want to post it publicly.
